---
apiVersion: v1
kind: Pod
metadata:
  name: worker
spec:
  containers:
    - name: build-worker
      image: "{{ images.builder }}"
      resources:
        requests:
          cpu: "250m"
          memory: 1Gi
        limits:
          cpu: "1"
          memory: 1Gi
      env:
        - name: DOCKER_HOST
          value: localhost:2375
      volumeMounts:
        - name: worker-workspace
          mountPath: /workdir
    - name: dind-daemon
      image: docker:18.09.6-dind
      resources:
        requests:
          cpu: "250m"
          memory: 1Gi
        limits:
          cpu: "1"
          memory: 1Gi
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-storage
          mountPath: /var/lib/docker
        - name: worker-workspace
          mountPath: /workdir
    - name: mongo
      image: scality/ci-mongo:3.6.8
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 1000m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 1Gi
  volumes:
    - name: docker-storage
      emptyDir: {}
    - name: worker-workspace
      emptyDir: {}
